force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <description>Billing Email from Converted Lead</description>
    <label>Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <description>Used to associate the Account with specific QuickBooks Terms (e.g., Net 30, Net 7)</description>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 7</fullName>
            </value>
            <value>
                <fullName>Net 10</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/Integration_Mapping__c.object-meta.xml
<CustomObject>
    <description>Centralized mapping table for QuickBooks Items, Classes, and Terms.</description>
    <label>Integration Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Mapping__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Identifies the type of QuickBooks entity being mapped. Values: Item, Class, Term.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Item</fullName>
            </value>
            <value>
                <fullName>Class</fullName>
            </value>
            <value>
                <fullName>Term</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The &apos;Description&apos; field from QBO. Primarily used for line item details in the Invoice Request payload.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>The &apos;FullyQualifiedName&apos; from QBO. Represents the hierarchical path of the record (e.g., Parent:Child), essential for accurate Item matching.</description>
    <label>Full Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Synchronized &apos;Active&apos; status from QBO. Checked if the record is valid for use in current business transactions.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/QBO_ID__c.field-meta.xml
<CustomField>
    <fullName>QBO_ID__c</fullName>
    <description>The raw internal ID (Primary Key) assigned to this record within QuickBooks Online</description>
    <label>QBO ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Mapping__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>The standard &apos;UnitPrice&apos; for Services or Products in QBO.</description>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Stores transactional data synchronized from QuickBooks Online after successful invoice creation.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{MM}{DD}{YY}-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Services_Needed__c/Services_Needed__c.object-meta.xml
<CustomObject>
    <description>Services Needed holds available service information for the Customers</description>
    <label>Services Needed</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>Services Needed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Services_Needed__c/fields/Connected_Fixture__c.field-meta.xml
<CustomField>
    <fullName>Connected_Fixture__c</fullName>
    <label>Connected Fixture</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Wok</fullName>
            </value>
            <value>
                <fullName>Dish Washer</fullName>
            </value>
            <value>
                <fullName>Mop</fullName>
            </value>
            <value>
                <fullName>multi-comp sink</fullName>
            </value>
            <value>
                <fullName>single-comp sink</fullName>
            </value>
            <value>
                <fullName>Spray Sink</fullName>
            </value>
            <value>
                <fullName>Dish Sink</fullName>
            </value>
            <value>
                <fullName>Prep Sink</fullName>
            </value>
            <value>
                <fullName>3 comp sink</fullName>
            </value>
            <value>
                <fullName>Multi Comp Sink</fullName>
                <isActive>false</isActive>
                <label>Multi Comp Sink</label>
            </value>
            <value>
                <fullName>Single Comp Sink</fullName>
                <isActive>false</isActive>
                <label>Single Comp Sink</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Services_Needed__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <description>Capture Volume for all services</description>
    <inlineHelpText>GRD/HYD/UCO service Size</inlineHelpText>
    <label>Volume / Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Services_Needed__c/recordTypes/Interceptor.recordType-meta.xml
<RecordType>
    <fullName>Interceptor</fullName>
    <active>true</active>
    <description>Interceptor</description>
    <label>Interceptor</label>
</RecordType>

force-app/main/default/objects/WorkOrder/fields/Connected_Fixture__c.field-meta.xml
<CustomField>
    <fullName>Connected_Fixture__c</fullName>
    <label>Connected Fixture</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Connected Fixture</fullName>
            </value>
            <value>
                <fullName>Wok</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Spray Sink</fullName>
            </value>
            <value>
                <fullName>Mop</fullName>
            </value>
            <value>
                <fullName>multi-comp sink</fullName>
            </value>
            <value>
                <fullName>single-comp sink</fullName>
            </value>
            <value>
                <fullName>Dish Sink</fullName>
            </value>
            <value>
                <fullName>Prep Sink</fullName>
            </value>
            <value>
                <fullName>3 comp sink</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Establishes the relationship where multiple Work Orders can be associated with a single consolidated Invoice record.</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service_Duration_In_Mins__c.field-meta.xml
<CustomField>
    <fullName>Service_Duration_In_Mins__c</fullName>
    <formula>(DATETIMEVALUE(SUBSTITUTE(Service_EndTime__c , &quot;T&quot;, &quot; &quot;) ) - DATETIMEVALUE( SUBSTITUTE(Service_StartTime__c , &quot;T&quot;, &quot; &quot;))) * 24 * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Duration (In Mins)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Services_Needed__c.field-meta.xml
<CustomField>
    <fullName>Services_Needed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Services Needed</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Services_Needed__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Services_Needed__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <description>Derived from Service Needed</description>
    <label>Volume / Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QBO_Selector.cls
/**
 * @description Consolidated Selector to fetch WorkOrders and Parent Details in one call.
 */
public with sharing class QBO_Selector {

    public static List<WorkOrder> getWorkOrdersForInvoices(Set<Id> invoiceIds) {
        return [SELECT Id, Invoice__c, Invoice__r.Name,
                Account.Name,Account.Customer_ID__c,Account.Payment_Term__c,Account.Billing_Email__c,Account.ShippingState,
                Services_Needed__r.RecordType.Name,Order_Date__c,Volume__c,Rate__c,Connected_Fixture__c,Service_Duration_In_Mins__c
                FROM WorkOrder 
                WHERE Invoice__c IN :invoiceIds ];
    }
    
    public static List<WorkOrder> getWorkOrdersById(List<Id> wIds) {
        return [SELECT Id, Invoice__c, Invoice__r.Name,
                Account.Name,Account.Customer_ID__c,Account.Payment_Term__c,Account.Billing_Email__c,Account.ShippingState,
                Services_Needed__r.RecordType.Name,Order_Date__c,Volume__c,Rate__c,Connected_Fixture__c,Service_Duration_In_Mins__c
                FROM WorkOrder 
                WHERE Id IN :wIds ];
    }
    
/**
 * @description Fetches all relevant mappings for Terms and Classes to prevent SOQL in loops.
 */
    public static Map<String, String> getIntegrationMappings(Set<String> terms,Set<String> classes,Set<String> items) {
        
        Map<String, String> integrationQBOIdMap = new Map<String, String>();
        Set<String> rts = new Set<String>();
        Set<String> volumes = new Set<String>();
        Set<Decimal> rates = new Set<Decimal>();
        
        for(String item : items){
            rts.add('%'+item.split('_')[0]+'%');
            volumes.add(item.split('_')[1]);
            rates.add(Decimal.valueOf(item.split('_')[2]));
        }
        
        system.debug(rts+'_'+volumes+'_'+rates);
        
        List<Integration_Mapping__c> intMap = [SELECT Id,Name, QBO_ID__c, Category__c, Full_Name__c, 
                                          Description__c, Unit_Price__c 
                                        FROM Integration_Mapping__c 
                                        WHERE Is_Active__c = true AND ( (Category__c = 'Term' AND Name IN :terms)
                                        OR (Category__c = 'Class' AND Name IN :classes)
                                        OR (Category__c = 'Item' AND Name LIKE :rts AND Description__c IN :volumes 
                                            AND Unit_Price__c IN :rates) )];
                                            
        for(Integration_Mapping__c m : intMap){
            String itemName;
            if(m.name.contains('Interceptor') || m.name.contains('INT')){
                    itemName = 'Interceptor';
                }else if(m.name.contains('Grease Trap')){
                    itemName = 'Grease Trap';
                }else if(m.name.contains('Waste Run')){
                    itemName = 'Waste Run';
                }else if(m.name.contains('Drain Cleaning') || m.name.contains('HYD')){
                    itemName = 'Drain Cleaning';
                }else{
                    itemName = 'Used Cooking Oil';
                }
            
            if(m.Category__c == 'Term' || m.Category__c == 'Class') {
                integrationQBOIdMap.put(m.Name, m.QBO_ID__c);
            }else{
                integrationQBOIdMap.put(itemName+'_'+ m.Description__c + '_' + m.Unit_Price__c, m.Full_Name__c + '_' +m.QBO_ID__c );
            }
        }                                          
        return integrationQBOIdMap;
    }
}