force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Stores transactional data synchronized from QuickBooks Online after successful invoice creation.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{MM}{DD}{YY}-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The date the payment is due, typically calculated via QBO based on Net Terms.</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Creation_Date__c</fullName>
    <description>The timestamp when the record was established in QBO (maps to time in response)</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <description>Current status of the invoice.</description>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Integration Error</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QBO_Invoice_ID__c.field-meta.xml
<CustomField>
    <fullName>QBO_Invoice_ID__c</fullName>
    <description>External ID &amp; Unique. The unique internal ID returned by QuickBooks (maps to Invoice.Id in response)</description>
    <externalId>true</externalId>
    <label>QBO Txn Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ready_for_Integration__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Integration Gatekeeper. When checked (True), signals to the Scheduled Batch that all related Work Orders for the Account/Date are completed and the record is ready for QuickBooks sync.</description>
    <label>Ready for Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_T__c.field-meta.xml
<CustomField>
    <fullName>Sales_T__c</fullName>
    <label>Sales tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>The final total calculated by the billing system (maps to TotalAmt)</description>
    <label>Invoice total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Establishes the relationship where multiple Work Orders can be associated with a single consolidated Invoice record.</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Requested</fullName>
                <default>true</default>
                <label>Not Requested</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Optimo_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Optimo_Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Optimo Order Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_Number_Display__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Number_Display__c</fullName>
    <formula>HYPERLINK(
    &quot;/lightning/r/WorkOrder/&quot; &amp; Id &amp; &quot;/view&quot;,
    IF(
        ISBLANK(Services_Needed__c),
        WorkOrderNumber,
        CASE(
            Services_Needed__r.RecordType.DeveloperName,
            &quot;Grease_Trap&quot;, &quot;IGT&quot;,
            &quot;Drain_Cleaning&quot;, &quot;HYD&quot;,
            &quot;Interceptor&quot;, &quot;EGT&quot;,
            &quot;Used_Cooking_Oil&quot;, &quot;UCO&quot;,
            &quot;Waste_Run&quot;,&quot;WR&quot;,
            &quot;&quot;
        )
        &amp; &quot;-&quot; &amp;
        WorkOrderNumber
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Order Number Display</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationResponseHandler.cls
/**
 * @description This class handles the response logic following a callout to Optimo Route.
 * It processes the HTTP response, parses the JSON results, and updates corresponding 
 * WorkOrder records with their new status and Optimo Order IDs.
 */

 public with sharing class IntegrationResponseHandler {
    
    /**
     * @description Processes the API response and updates WorkOrder statuses.
     * @param res The HttpResponse object received from the Optimo API.
     * @param woIds A set of IDs for the WorkOrders that were included in the request.
     */

    public static void handleOptimoResponse(HttpResponse res, Set<Id> woIds) {
        try{

            // Map to store successful Order Numbers and their returned Optimo IDs
            Map<String,String> mapOfWOandOptimoId = new Map<String,String>();
            
            // Retrieve the WorkOrder records to be updated
            List<WorkOrder> listOfWOs = GetObjectSOQL.getWorkOrderNumbers(woIds); 

            //if response is 200, success is true then update the work order status to Unscheduled and optimo order id else update the work order status to Integration Error
            // 1. Process successful response
            if(res != null && res.getStatusCode() == 200){
                OptimoRouteWrapperResponseClass optimoWrapResponse = (OptimoRouteWrapperResponseClass)JSON.deserialize(res.getBody(),OptimoRouteWrapperResponseClass.class);
                System.debug('Response Body>'+res.getBody());
                if(optimoWrapResponse.success && optimoWrapResponse.orders != null ){
                    for(OptimoRouteWrapperResponseClass.cls_orders order : optimoWrapResponse.orders){
                        if(order.success){
                            mapOfWOandOptimoId.put(order.orderNo,order.id);
                        }
                    }
                }
            }
            // 2. Map statuses based on results
            // Using a single loop to determine the status of EVERY record in the batch.
            // This handles partial success: some may be 'Unscheduled' while others are 'Integration Error'.
            for (WorkOrder wo : listOfWOs) {
                //if (mapOfWOandOptimoId.containsKey(wo.WorkOrderNumber)) { // changed into display
                if (mapOfWOandOptimoId.containsKey(wo.Work_Order_Number_Display__c.substringBetween('>', '</a>'))) {
                    wo.Status = 'Unscheduled';
                    //wo.Optimo_Order_Id__c = mapOfWOandOptimoId.get(wo.WorkOrderNumber); // get with workorder display
                    wo.Optimo_Order_Id__c = mapOfWOandOptimoId.get(wo.Work_Order_Number_Display__c.substringBetween('>', '</a>'));
                } else {
                    // This captures both 400/500 errors AND specific order failures
                    wo.Status = 'Integration Error';
                }
            }    
            
            // STEP 3: Database Update
            if(!listOfWOs.isEmpty()){
                // allOrNone = false allows successful records to save even if others fail DML
                // AccessLevel.USER_MODE ensures Field Level Security (FLS) is respected
                Database.SaveResult[] woList = Database.update(listOfWOs,false,AccessLevel.USER_MODE);
                
                // Log specific DML errors (e.g., validation rule failures)
                for(Database.SaveResult sr : woList){
                    if(!sr.isSuccess()){
                        System.debug(LoggingLevel.ERROR, 'DML Error: ' + sr.getErrors()[0].getMessage());
                    }
                }
            }

        }
        catch(Exception ex){
            // Comprehensive error logging including the stack trace for easier debugging
            System.debug(LoggingLevel.ERROR, 'Exception: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
        }
    }
     
/**
 * @description Processes a single QBO API response and updates the corresponding Invoice.
 * @param res The HttpResponse from MuleSoft/QBO.
 * @param invoiceIds The set containing the Invoice ID processed in the callout.
 */
public static void handleQBOResponse(HttpResponse res, Set<Id> invoiceIds) {
    try {
        // 1. Fetch Invoices to be updated
        Map<String, Invoice__c> invoiceMap = new Map<String, Invoice__c>();
        for (Invoice__c inv : [SELECT Id, Name, Invoice_Status__c, QBO_Invoice_ID__c, Ready_for_Integration__c ,
                               Total_Amount__c , Invoice_Creation_Date__c , Due_Date__c, Sales_T__c, Subtotal__c
                               FROM Invoice__c 
                               WHERE Id IN :invoiceIds WITH USER_MODE]) {
            invoiceMap.put(inv.Name, inv);
        }

        if (res != null && (res.getStatusCode() == 200 || res.getStatusCode() == 201)) {
            // 2. Deserialize as a single Object instead of a List
            QBO_InvoiceResponseWrapper wrapper = (QBO_InvoiceResponseWrapper)JSON.deserialize(
                res.getBody(), 
                QBO_InvoiceResponseWrapper.class
            );

            if (wrapper != null && wrapper.Invoice != null) {
                QBO_InvoiceResponseWrapper.Invoice qboInv = wrapper.Invoice;
                
                // Use DocNumber (Invoice Name) to find the correct Salesforce record
                if (invoiceMap.containsKey(qboInv.DocNumber)) {
                    Invoice__c sfInv = invoiceMap.get(qboInv.DocNumber);
                    sfInv.Invoice_Status__c = 'Created';
                    sfInv.QBO_Invoice_ID__c = qboInv.Id; // Mapping the QBO internal ID
                    sfInv.Ready_for_Integration__c = false; // Reset gatekeeper to stop re-syncing
                    sfInv.Total_Amount__c  = qboInv.TotalAmt;
                    
                    if (String.isNotBlank(qboInv.DueDate)) {
                        sfInv.Due_Date__c = Date.valueOf(qboInv.DueDate); // Captures "2026-05-06"
                    }
                    
                    if (String.isNotBlank(qboInv.TxnDate)) {
                        // Maps "2026-04-06" to Salesforce Date field
                        sfInv.Invoice_Creation_Date__c = Date.valueOf(qboInv.TxnDate); 
                    }
                    
                    if (qboInv.TxnTaxDetail != null) {
                        sfInv.Sales_T__c = qboInv.TxnTaxDetail.TotalTax;
                    }
                    sfInv.Subtotal__c = sfInv.Total_Amount__c - sfInv.Sales_T__c ;
                }
            }
        } else {
            // 3. Mark all records in this request as error if the callout failed
            for (Invoice__c inv : invoiceMap.values()) {
                inv.Invoice_Status__c = 'Integration Error';
            }
        }

        // 4. Update Database
        if (!invoiceMap.isEmpty()) {
            Database.update(invoiceMap.values(), false, AccessLevel.USER_MODE);
        }
    } catch (Exception ex) {
        System.debug(LoggingLevel.ERROR, 'QBO Response Exception: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
    }
}
}